# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141010)
$foreground = rgb(D7AEB2)
$color0 = rgb(3C3838)
$color1 = rgb(170908)
$color2 = rgb(140B0A)
$color3 = rgb(140B0B)
$color4 = rgb(190B0C)
$color5 = rgb(4F0F16)
$color6 = rgb(6A111B)
$color7 = rgb(BE8389)
$color8 = rgb(855B60)
$color9 = rgb(1E0B0A)
$color10 = rgb(1B0E0E)
$color11 = rgb(1A0F0E)
$color12 = rgb(220F0F)
$color13 = rgb(6A141D)
$color14 = rgb(8E1724)
$color15 = rgb(BE8389)
